# Generated by Django 4.0.1 on 2022-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descargas',
            name='enlace',
            field=models.URLField(default='/https:wikipedia'),
        ),
    ]
