# Generated by Django 4.0.1 on 2022-03-02 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscord', '0002_descargas_enlace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_act', models.CharField(max_length=100)),
                ('fecha_act', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
