# Generated by Django 4.0.1 on 2022-03-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscord', '0003_actualizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
